name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: npm install
        env:
          CI: true
        run: npm ci
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # zip
          zip -r webp.zip .
          # aws cli - deploy code
          aws s3 cp --region us-east-1 webp.zip s3://webp-zip
          aws lambda update-function-code --region us-east-1 --function-name webp --s3-bucket webp-zip --s3-key webp.zip --version 17

