name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: npm install
        env:
          CI: true
        run: npm ci
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CLOUDFRONT_ID: "E2WIUYQR3SAQ2K"
          LAMBDA_VERSION_FILE: version.json
          GET_CLOUDFRONT_CONFIG: config.json
          DISTRIBUTION_CLOUDFRONT_CONFIG: distrib-config.json
          ETAG: eTag.txt
        run: |
          aws --version
          # zip
          SET = $(seq 1 200)
          for i in $SET
          do    
            aws glue delete-job --job okcoy$i
          done
